### ISSUE TITLE
renaming protoc_installer to protobuf_compiler breaks the other packages

### ISSUE THREAD

**Issue by schnapper79** [0x8000-0000/conan-recipes#2]
Hi @0x8000-0000 ,

first of all, great work. Thanks for making these conan recipes. This finally made me leave vcpkg and move on to conan

Your last commit (6d504de), renaming the package for the protobuf compiler broke the dependency in gRpc - recipe and the test. I added a pull request #1

**Comment by 0x8000-0000** [comment]
Hi @schnapper79 

My apologies for breaking the repository; I was in the middle of a refactoring, extracting the grpc_plugin out of grpc package so they can be built with different compilers or configuration (think embedded or static linking.) and I was not mindful that somebody else might have found this repository useful. I should have been more careful.

I have merged the pull request and will update the documentation. I will push the work in progress in a separate branch so you can see where it is going.

Thank you for the fix!
